name: media_app
description: Application de gestion de médias
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  adaptive_navigation: ^0.0.3
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  url_strategy: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/films/
    - assets/imgs/livres/
    - assets/imgs/series/
    - assets/medias.json